package com.nhz.shared

const val specialities = "specialities"
const val medicines = "medicines"
const val questions = "questions"
const val patients = "patients"
const val general_questions_and_answers = "general_questions_and_answers"
const val recent_doctors = "recent_doctors"
const val general_questions = "general_questions"
const val doctors = "doctors"
const val consultations = "consultations"
const val case_summary = "case_summary"
const val conversations = "conversations"
const val prescriptions = "prescriptions"
const val consultation_requests = "consultation_requests"
const val checkOut = "checkout"
